### ISSUE TITLE
Error while using tspy package

### ISSUE THREAD

**Issue by skantbksc** [wborgeaud/tspy#1]
D =   [[  0,  60,  66, 258, 256, 682, 770, 888],
       [ 60,   0,  50, 225, 213, 630, 719, 832],
       [ 66,  50,   0, 275, 260, 618, 707, 829],
       [258, 225, 275,   0,  52, 689, 772, 840],
       [256, 213, 260,  52,   0, 637, 719, 789],
       [682, 630, 618, 689, 637,   0,  88, 245],
       [770, 719, 707, 772, 719,  88,   0, 181],
       [888, 832, 829, 840, 789, 245, 181,   0]]

from tspy import TSP
tsp = TSP()

tsp.read_mat(D)

from tspy.solvers import TwoOpt_solver
two_opt = TwoOpt_solver(initial_tour='NN', iter_num=100)
two_opt_tour = tsp.get_approx_solution(two_opt)

The code does not exceute and gives the following error:
TypeError: list indices must be integers or slices, not tuple

**Comment by wborgeaud** [comment]
The problem is that `read_mat` takes a **numpy** matrix as argument (this is mentioned in the docs). 
If you replace the first line by
```python
import numpy as np
D = np.array([[...],...,[...]], np.float64)
```
the code runs as expected.
